# path to a directory with all packages
storage: ../tmp/local-registry/storage

auth:
  htpasswd:
    file: ./htpasswd
    algorithm: bcrypt

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m
    max_fails: 20
    fail_timeout: 2m
  yarn:
    url: https://registry.yarnpkg.com
    maxage: 60m
    max_fails: 20
    fail_timeout: 2

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    # give all users (including non-authenticated users) full access
    # because it is a local registry
    access: $all
    publish: $all
    unpublish: $all

    # if package is not available locally, proxy requests to npm registry
    proxy: npmjs

# log settings
logs:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true # set offline to true to allow publish offline
