name: CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  node_version: 20

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/setup
        with:
          node_version: ${{ env.node_version }}
      - run: yarn nx affected --target=build,test,lint  --exclude monodon --parallel --max-parallel=3
      - run: yarn nx affected --target=e2e --exclude monodon --parallel
      - run: yarn nx-cloud stop-all-agents
